import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/header';
import Footer from '../components/footer';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-slate-50 dark:bg-slate-900 text-slate-700 w-screen h-screen dark:text-slate-300 flex flex-col justify-center items-center`}>
				<Toaster position='bottom-center' />
        <Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
